name: Issue Report
description: File an issue report
title: "[Issue]: "
labels: ["issue", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report! Please ensure you've read our [documentation](https://docs.hydra.so/).
        If you're unsure as to whether or not you're experiencing an issue, please reach out on our [Discord](https://discord.com/invite/SQrwnAxtDw) to gain a better understanding
        of what you're facing.

  - type: checkboxes
    id: checks
    attributes:
      label: First check
      description: Please confirm and check all the following options.
      options:
        - label: I added a descriptive title to this issue.
          required: true
        - label: I used the GitHub search to find a similar issue and didn't find it.
          required: true
        - label: I searched the Hydra documentation for this issue.
          required: true
        - label: I checked that this issue is related to Hydra and not one of its dependencies.
          required: true

  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more info?
      placeholder: ex. email@example.com
    validations:
      required: false
      
  - type: textarea
    attributes:
      label: Issue summary
      description: A clear and concise description of what the issue is.
      placeholder: "# Tell us what you see!"
    validations:
      required: true      
      
  - type: textarea
    attributes:
      label: Reproduction
      description:  >
        Provide your [minimal, complete, and verifiable](https://stackoverflow.com/help/mcve) example here. 
      placeholder: "# Insert here"
    validations:
      required: false
      
  - type: textarea
    attributes:
      label: Issue message
      description:  >
        Provide your [minimal, complete, and verifiable](https://stackoverflow.com/help/mcve) example here. 
      placeholder: "# Insert here"
    validations:
      required: false
      
  - type: textarea
    attributes:
      label: Version
      description:  >
        Run `SELECT VERSION()` to retreive your Hydra version. 
      placeholder: "# Insert here"
    validations:
      required: true
 
   - type: textarea
    attributes:
      label: Additional context
      description:  >
        Add any other context about the problem here.
      placeholder: "# Insert here"
    validations:
      required: false
