blank_issues_enabled: false
contact_links:
  - name: 📖 Read the documentation
    url: https://docs.hydra.so/
    about: Please consult the documentation before opening any issues!
  - name: 🙋 Ask a question on Discord
    url: https://discord.com/invite/SQrwnAxtDw
    about: Ask questions about how to use Hydra on our Discord (and show off your cute pets on our hydra-pets channel!).
